### ISSUE TITLE
3.3.8: Network view is frozen after pathway import

### ISSUE THREAD

**Issue by khanspers** [wikipathways/cytoscape-wikipathways-app#118] opened 2022-01-11 00:09 UTC
After importing a pathway from WP (WP179) the network view seems to freeze during rendering at a stage before the view is updated to fit content. See attached. The interface is mostly frozen at this point, I can't resize Cytoscape for example, and clicking away from the network and then back again results in a totally blank view. I can access all menus and the Table Panel seems un effected.

<img width="1299" alt="Screen Shot 2022-01-10 at 4 04 50 PM" src="https://user-images.githubusercontent.com/1442197/148858574-39a524d6-7390-426e-a0e5-c30dd1825bd1.png">

**Comment by AlexanderPico** [comment] 2022-01-11 00:36
Could not reproduce. WP179 opened as pathway and as network just fine. 

Do you see this with 'open as pathway' too? Do you see this with other WPIDs?  Can you reproduce this?

**Comment by AlexanderPico** [comment] 2022-01-11 00:36
If you can reproduce, then run with Cytoscape launched via command line so you can report the stack trace.

**Comment by khanspers** [comment] 2022-01-11 00:57
OK, A couple of weird things:

1. If I open another pathway first (tried several), it works with that pathway and also human Cell Cycle (WP179).
2. In the above scenario, opening as network also works.
3. If I open WP 179 first (freshly launched Cytoscape), I get the error. Import as network also doesn't work for this case.
4. I can't launch Cytoscape 3.9.0 from command line, I get:

Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/cytoscape/launcher/internal/Launcher has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:601)

**Comment by AlexanderPico** [comment] 2022-01-11 01:10
Weird, indeed!  Maybe install the old WP app and try it out? I suspect these issues are not related to the new 3.3.8, but I can't be sure...

**Comment by ariutta** [comment] 2022-01-11 19:12
With Cytoscape 3.9.1-rc1 and WP App 3.3.8, I see the same thing as @khanspers.

I'm on macOS 11.6.2.

**Comment by ariutta** [comment] 2022-01-11 19:16
I launched Cytoscape from the icon and loaded WP179 via the WP App. The pathway was not fully visible, similar to what @khanspers described.
![image](https://user-images.githubusercontent.com/1296771/149006818-c63f0bb2-a0b4-43de-b9ae-55f99401d8fd.png)

The zoom buttons didn't respond. When I clicked the Apply Preferred Layout button, I got this error message:
![image](https://user-images.githubusercontent.com/1296771/149006573-fc0ab4b2-3d7b-41d5-b917-2bf276295129.png)

**Comment by ariutta** [comment] 2022-01-11 19:19
I was able to zoom in/out when I opened WP179 via the NDEx App.

**Comment by ariutta** [comment] 2022-01-11 19:21
Like @khanspers, I was able to import WP179 as pathway via WP App when I first opened a different pathway beforehand. When I first opened WP179 from the NDEx App, and I was able to zoom in/out for that pathway, and I was also able to open WP179 from the WikiPathways App, and zoom in/out worked.

**Comment by ariutta** [comment] 2022-01-11 19:33
I tried uninstalling the WP App and launching Cytoscape from the command line, but I still get the same error, regardless of whether I try launching 3.9.1 or 3.8.2.

**Comment by ariutta** [comment] 2022-01-11 19:56
In `CytoscapeConfiguration/3/framework-cytoscape.log`, here's the error log corresponding to the error in the screenshot above:
>2022-01-11 11:54:04,798 [Task-Thread-6-Factory-0x4dc5232d] WARN  org.cytoscape.application.userlog - Caught exception executing task. 
java.lang.ClassCastException: class java.lang.String cannot be cast to class org.cytoscape.view.presentation.property.values.Bend (java.lang.String is in module java.base of loader 'bootstrap'; org.cytoscape.view.presentation.property.values.Bend is in unnamed module of loader org.apache.felix.framework.BundleWiringImpl$BundleClassLoader @2751e557)
        at org.cytoscape.view.layout.LayoutEdit.saveEdgeViews(LayoutEdit.java:130) ~[?:?]
        at org.cytoscape.view.layout.LayoutEdit.<init>(LayoutEdit.java:77) ~[?:?]
        at org.cytoscape.view.layout.AbstractLayoutTask.run(AbstractLayoutTask.java:149) ~[?:?]
        at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.innerRun(JDialogTaskManager.java:337) ~[!/:?]
        at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.run(JDialogTaskManager.java:352) [!/:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by yihangx** [comment] 2022-01-12 01:47
I tried WikiPathways 3.3.8 and Cytoscape 3.9.1 with Windows 11, and I got same error. However, I cannot reproduce it on my macOS Catalina with WikiPathways 3.3.8 and Cytoscape 3.9.1.

**Comment by yihangx** [comment] 2022-01-12 01:59
Did more research here. WikiPathways 3.3.7 do not have this error on my both machine. I doubt it is  a 3.3.8 issue.

**Comment by AlexanderPico** [comment] 2022-03-17 23:47
This is fixed in the new [3.3.9 release](https://apps.cytoscape.org/apps/wikipathways)

**Closed by AlexanderPico** 2022-03-17 23:47 UTC
Labels: bug
