### ISSUE TITLE
The cellular compartment should be an annotation, not a node

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/cytoscape-wikipathways-app#39] opened 2017-08-03 23:38 UTC
Opening WP430, we can see that the main cellular compartment shape for the Liver cell is a node, not an annotation. Click on it and see the Node Table display the properties of the node. Right click on it and see there are no options to edit Annotation, etc.

We have code in place to make annotation from GPML shapes, but it is not doing it...
https://github.com/wikipathways/cytoscape-wikipathways-app/blob/newBranch/src/main/java/org/wikipathways/cytoscapeapp/DelayedVizProp.java#L130

**Comment by AdamStuart** [comment] 2017-08-04 18:03
Duplicate of #30

**Closed by AdamStuart** 2017-08-04 18:03 UTC
Labels: bug
